// company data
export const REQUEST_COMPANY_DATA = 'REQUEST_COMPANY_DATA';
export const RECEIVE_COMPANY_DATA = 'RECEIVE_COMPANY_DATA';
// rockets data
export const REQUEST_ROCKETS_DATA = 'REQUEST_ROCKETS_DATA';
export const RECEIVE_ROCKETS_DATA = 'RECEIVE_ROCKETS_DATA';
