// company
export const REQUEST_COMPANY_DATA = 'REQUEST_COMPANY_DATA';
export const RECEIVE_COMPANY_DATA = 'RECEIVE_COMPANY_DATA';

// rockets
export const REQUEST_ROCKETS_DATA = 'REQUEST_ROCKETS_DATA';
export const RECEIVE_ROCKETS_DATA = 'RECEIVE_ROCKETS_DATA';

// launches
export const REQUEST_LAUNCHES_DATA = 'REQUEST_LAUNCHES_DATA';
export const RECEIVE_LAUNCHES_DATA = 'RECEIVE_LAUNCHES_DATA';
export const TOGGLE_LAUNCHES_MODE = 'TOGGLE_LAUNCHES_MODE';
export const CHANGE_LAUNCH_YEAR = 'CHANGE_LAUNCH_YEAR';

// measurement system
export const TOGGLE_METRIC_SYSTEM = 'TOGGLE_METRIC_SYSTEM';
